version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
